Repository openshift/runbooks, pull requests merged in 2023-07, with the labels that each got.

#125 OCPBUGS-12760: Add PrometheusRemoteStorageFailures runbook
  alerts/cluster-monitoring-operator/PrometheusRemoteStorageFailures.md
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#128 Fix KubemacpoolDown runbook
  alerts/openshift-virtualization-operator/KubemacpoolDown.md
Labels: needs-ok-to-test, approved, lgtm

#127 CNV-30692: VirtualMachineCRCErrors runbook
  alerts/openshift-virtualization-operator/VirtualMachineCRCErrors.md
Labels: approved, lgtm, jira/valid-reference

#129 CNV-30825: add KubevirtHCOSingleStackIPv6 runboook
  alerts/openshift-virtualization-operator/KubevirtHCOSingleStackIPv6.md
Labels: approved, lgtm, jira/valid-reference

#130 Update KubevirtHcoSingleStackIPv6
  alerts/openshift-virtualization-operator/KubevirtHCOSingleStackIPv6.md
  alerts/openshift-virtualization-operator/KubevirtHcoSingleStackIPv6.md
Labels: approved, lgtm

#131 CNV-31194: rename HCO alerts
  alerts/openshift-virtualization-operator/HCOInstallationIncomplete.md
  alerts/openshift-virtualization-operator/KubeVirtCRModified.md
  alerts/openshift-virtualization-operator/SingleStackIPv6Unsupported.md
  alerts/openshift-virtualization-operator/UnsupportedHCOModification.md
Labels: approved, lgtm, jira/valid-reference
