Repository openshift/runbooks, pull requests merged in 2023-12, with the labels that each got.

#147 odf native alerts runbooks
  alerts/openshift-container-storage-operator/KMSServerConnectionAlert.md
  alerts/openshift-container-storage-operator/ODFRBDClientBlocked.md
  alerts/openshift-container-storage-operator/OdfMirrorDaemonStatus.md
  alerts/openshift-container-storage-operator/OdfPoolMirroringImageHealth.md
Labels: ok-to-test, approved, lgtm

#151 CNV-35840: VirtHandlerRESTErrorsHigh update
  alerts/openshift-virtualization-operator/VirtHandlerRESTErrorsHigh.md
Labels: approved, lgtm, jira/valid-reference

#150 add documentation for alerts related to ceph osd
  alerts/openshift-container-storage-operator/CephClusterErrorState.md
  alerts/openshift-container-storage-operator/CephClusterWarningState.md
  alerts/openshift-container-storage-operator/CephDataRecoveryTakingTooLong.md
  alerts/openshift-container-storage-operator/CephMonVersionMismatch.md
  alerts/openshift-container-storage-operator/CephOSDDiskNotResponding.md
  alerts/openshift-container-storage-operator/CephOSDDiskUnavailable.md
  alerts/openshift-container-storage-operator/CephOSDFlapping.md
  alerts/openshift-container-storage-operator/CephOSDNearFull.md
  alerts/openshift-container-storage-operator/CephOSDSlowOps.md
  alerts/openshift-container-storage-operator/CephOSDVersionMismatch.md
  alerts/openshift-container-storage-operator/CephPgRepairTakingTooLong.md
  alerts/openshift-container-storage-operator/ODFPersistentVolumeMirrorStatus.md
  alerts/openshift-container-storage-operator/ObcQuotaBytesAlert.md
  alerts/openshift-container-storage-operator/OdfMirrorDaemonStatus.md
  alerts/openshift-container-storage-operator/OdfPoolMirroringImageHealth.md
  alerts/openshift-container-storage-operator/PersistentVolumeUsageNearFull.md
  alerts/openshift-container-storage-operator/helpers/determineFailedOcsNode.md
Labels: ok-to-test, approved, lgtm

#146 Add runbook help for next set of alerts
  alerts/openshift-container-storage-operator/CephMdsMissingReplicas.md
  alerts/openshift-container-storage-operator/CephMgrIsAbsent.md
  alerts/openshift-container-storage-operator/CephMgrIsMissingReplicas.md
  alerts/openshift-container-storage-operator/CephMonHighNumberOfLeaderChanges.md
  alerts/openshift-container-storage-operator/CephMonQuorumAtRisk.md
  alerts/openshift-container-storage-operator/CephMonQuorumLost.md
  alerts/openshift-container-storage-operator/CephNodeDown.md
  alerts/openshift-container-storage-operator/CephOSDCriticallyFull.md
  alerts/openshift-container-storage-operator/ClusterObjectStoreState.md
  alerts/openshift-container-storage-operator/ObcQuotaBytesExhausedAlert.md
  alerts/openshift-container-storage-operator/ObcQuotaObjectsAlert.md
  alerts/openshift-container-storage-operator/ObcQuotaObjectsExhausedAlert.md
  alerts/openshift-container-storage-operator/helpers/accessToolbox.md
  alerts/openshift-container-storage-operator/helpers/sre-to-engineering-escalation.md
Labels: approved, lgtm

#126 [MON-2358] add alert PrometheusOperatorRejectedResources
  alerts/cluster-monitoring-operator/PrometheusOperatorRejectedResources.md
Labels: approved, lgtm, lifecycle/stale

#137 MON-2853: add alert "TargetDown"
  alerts/cluster-monitoring-operator/TargetDown.md
Labels: approved, lgtm, jira/valid-reference

#152 CNV-36233: fix OutdatedVirtualMachineInstanceWorkloads
  alerts/openshift-virtualization-operator/OutdatedVirtualMachineInstanceWorkloads.md
Labels: approved, lgtm, jira/valid-reference

#153 CNV-36239: CDINoDefaultStorageClass
  alerts/openshift-virtualization-operator/CDINoDefaultStorageClass.md
Labels: approved, lgtm, jira/valid-reference
