Repository openshift/runbooks, pull requests merged in 2024-11, with the labels that each got.

#216 Add runbook for StorageQuotaUtilizationThresholdReached
  alerts/openshift-container-storage-operator/StorageQuotaUtilizationThresholdReached.md
  alerts/openshift-container-storage-operator/helpers/screenshots/quota-increase.png
  alerts/openshift-container-storage-operator/helpers/screenshots/storage-client-list.png
Labels: ok-to-test, approved, lgtm

#222 alerts: add diretory structure and OWNERS for image registry
  alerts/cluster-image-registry-operator/OWNERS
Labels: approved, lgtm

#221 IR-509: add runbooks for cluster-image-registry-operator alerts
  alerts/cluster-image-registry-operator/ImageRegistryStorageFull.md
  alerts/cluster-image-registry-operator/ImageRegistryStorageReadOnly.md
Labels: approved, lgtm, qe-approved, jira/valid-reference

#217 Add two new alert runbook docs
  alerts/openshift-container-storage-operator/CephMdsCPUUsageHighNeedsHorizontalScaling.md
  alerts/openshift-container-storage-operator/CephMdsCPUUsageHighNeedsVerticalScaling.md
Labels: approved, lgtm

#224 Update OWNERS - Add avlitman
  alerts/openshift-virtualization-operator/OWNERS
Labels: approved, lgtm
