Repository openshift/runbooks, pull requests merged in 2024-06, with the labels that each got.

#185 NO-JIRA: fix label selectors for some 'oc logs' commands
  alerts/cluster-monitoring-operator/PrometheusRuleFailures.md
  alerts/cluster-monitoring-operator/PrometheusTargetSyncFailure.md
Labels: approved, lgtm, jira/valid-reference

#187 OCPBUGS-33758: Add and update CNO runbooks for ovnk-ic
  alerts/cluster-network-operator/NoOvnClusterManagerLeader.md
  alerts/cluster-network-operator/NoOvnMasterLeader.md
  alerts/cluster-network-operator/NoRunningOvnControlPlane.md
  alerts/cluster-network-operator/NoRunningOvnMaster.md
  alerts/cluster-network-operator/NorthboundStaleAlert.md
  alerts/cluster-network-operator/OVNKubernetesControllerDisconnectedSouthboundDatabase.md
  alerts/cluster-network-operator/OVNKubernetesNorthdInactive.md
  alerts/cluster-network-operator/SouthboundStaleAlert.md
  alerts/cluster-network-operator/hierarchy/alerts-hierarchy.dot
  alerts/cluster-network-operator/hierarchy/alerts-hierarchy.svg
Labels: approved, lgtm, jira/severity-low, jira/valid-bug, jira/valid-reference

#186 Removing PV usage percentage numbers from runbooks doc text
  alerts/openshift-container-storage-operator/PersistentVolumeUsageCritical.md
  alerts/openshift-container-storage-operator/PersistentVolumeUsageNearFull.md
Labels: approved, lgtm

#178 ETCD-586: add runbook entry for etcd-ca expiration alert
  alerts/cluster-etcd-operator/OWNERS
  alerts/cluster-etcd-operator/etcdSignerCAExpirationCritical.md
Labels: approved, lgtm, jira/valid-reference
