Repository openshift/runbooks, pull requests merged in 2024-07, with the labels that each got.

#189 Modify MDS CPU runbook to scale mds pods.
  alerts/openshift-container-storage-operator/CephMdsCpuUsageHigh.md
Labels: ok-to-test, approved, lgtm

#195 OCPBUGS-36495: Add runbook for ClusterMonitoringOperatorDeprecatedConfig
  alerts/cluster-monitoring-operator/ClusterMonitoringOperatorDeprecatedConfig.md
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#199 OCPBUGS-36495: Update alert desc in ClusterMonitoringOperatorDeprecatedConfig
  alerts/cluster-monitoring-operator/ClusterMonitoringOperatorDeprecatedConfig.md
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#201 [CNV] Move deprecated runbooks back to the general list
  alerts/openshift-virtualization-operator/KubeVirtComponentExceedsRequestedCPU.md
  alerts/openshift-virtualization-operator/KubeVirtComponentExceedsRequestedMemory.md
  alerts/openshift-virtualization-operator/VirtualMachineCRCErrors.md
  alerts/openshift-virtualization-operator/deprecated/KubeVirtComponentExceedsRequestedCPU.md
  alerts/openshift-virtualization-operator/deprecated/KubeVirtComponentExceedsRequestedMemory.md
  alerts/openshift-virtualization-operator/deprecated/VirtualMachineCRCErrors.md
Labels: approved, lgtm

#202 alert: correct mds high cpu usage patch command
  alerts/openshift-container-storage-operator/CephMdsCpuUsageHigh.md
Labels: approved, lgtm
