Repository openshift/runbooks, pull requests merged in 2024-01, with the labels that each got.

#139 Update NodeClockNotSynchronising.md
  alerts/cluster-monitoring-operator/NodeClockNotSynchronising.md
Labels: approved, lgtm

#154 CNV-36956: Add link to VM CRC errors runbook
  alerts/openshift-virtualization-operator/VirtualMachineCRCErrors.md
Labels: approved, lgtm, jira/valid-reference

#157 Fix CephMonVersionMismatch typo an broken link
  alerts/openshift-container-storage-operator/CephMonVersionMismatch.md
Labels: ok-to-test, approved, lgtm

#156 Fix CephClusterReadOnly alert title
  alerts/openshift-container-storage-operator/CephClusterReadOnly.md
Labels: ok-to-test, approved, lgtm

#158 fix incorrect restart times in the alert documetation
  alerts/openshift-container-storage-operator/CephOSDFlapping.md
Labels: ok-to-test, approved, lgtm

#159 Added OCS CephMonLowNumber alert
  alerts/openshift-container-storage-operator/CephMonLowNumber.md
Labels: ok-to-test, approved, lgtm

#162 Add runbooks for CephMdsCpuUsageHigh
  alerts/openshift-container-storage-operator/CephMdsCpuUsageHigh.md
Labels: ok-to-test, approved, lgtm

#160 Add runbooks for CephMdsCacheUsageHigh
  alerts/openshift-container-storage-operator/CephMdsCacheUsageHigh.md
Labels: approved, lgtm

#163 Some minor corrections in the alerts documentation
  alerts/openshift-container-storage-operator/CephOSDNearFull.md
  alerts/openshift-container-storage-operator/ClusterObjectStoreState.md
  alerts/openshift-container-storage-operator/ObcQuotaBytesExhausedAlert.md
  alerts/openshift-container-storage-operator/ObcQuotaObjectsAlert.md
  alerts/openshift-container-storage-operator/ObcQuotaObjectsExhausedAlert.md
Labels: approved, lgtm
