Repository openshift/runbooks, pull requests merged in 2025-03, with the labels that each got.

#238 OCPBUGS-51193: Add runbook for CoreDNSErrorsHigh
  alerts/cluster-dns-operator/CoreDNSErrorsHigh.md
  alerts/cluster-dns-operator/OWNERS
Labels: needs-ok-to-test, approved, lgtm, qe-approved, jira/severity-low, jira/valid-bug, jira/valid-reference

#231 Update openshift-virtualization-operator runbook
  alerts/openshift-virtualization-operator/CDIStorageProfilesIncomplete.md
  alerts/openshift-virtualization-operator/KubeVirtVMIExcessiveMigrations.md
  alerts/openshift-virtualization-operator/LowReadyVirtControllersCount.md
  alerts/openshift-virtualization-operator/LowReadyVirtOperatorsCount.md
  alerts/openshift-virtualization-operator/LowVirtAPICount.md
  alerts/openshift-virtualization-operator/LowVirtControllersCount.md
  alerts/openshift-virtualization-operator/LowVirtOperatorCount.md
  alerts/openshift-virtualization-operator/NetworkAddonsConfigNotReady.md
  alerts/openshift-virtualization-operator/NoLeadingVirtOperator.md
  alerts/openshift-virtualization-operator/NoReadyVirtController.md
  alerts/openshift-virtualization-operator/NoReadyVirtOperator.md
  alerts/openshift-virtualization-operator/OrphanedVirtualMachineInstances.md
  alerts/openshift-virtualization-operator/OutdatedVirtualMachineInstanceWorkloads.md
  alerts/openshift-virtualization-operator/VirtAPIDown.md
  alerts/openshift-virtualization-operator/VirtApiRESTErrorsBurst.md
  alerts/openshift-virtualization-operator/VirtApiRESTErrorsHigh.md
  alerts/openshift-virtualization-operator/VirtControllerDown.md
  alerts/openshift-virtualization-operator/VirtControllerRESTErrorsBurst.md
  alerts/openshift-virtualization-operator/VirtControllerRESTErrorsHigh.md
  alerts/openshift-virtualization-operator/VirtHandlerDaemonSetRolloutFailing.md
  alerts/openshift-virtualization-operator/VirtHandlerRESTErrorsBurst.md
  alerts/openshift-virtualization-operator/VirtHandlerRESTErrorsHigh.md
  alerts/openshift-virtualization-operator/VirtOperatorDown.md
  alerts/openshift-virtualization-operator/VirtOperatorRESTErrorsBurst.md
  alerts/openshift-virtualization-operator/VirtOperatorRESTErrorsHigh.md
Labels: ok-to-test, approved, lgtm

#243 add runbook for StorageAutoScaler alerts
  alerts/openshift-container-storage-operator/StorageAutoScalingCapacityReached.md
  alerts/openshift-container-storage-operator/StorageAutoScalingFailed.md
Labels: approved, lgtm
